package com.bank.aisafetyops.model;

/**
 * Window-level quality signal derived from emitted guardrail aggregates.
 *
 * <p>This record is intentionally separate from business aggregates so teams can
 * monitor the quality of guardrail detectors independently from the risk signal
 * generated by end users and agents.
 */
public record GuardrailQualityMetric(
        String tenantId,
        String agentId,
        String guardrailName,
        String guardrailVersion,
        String policyVersion,
        String modelName,
        String windowName,
        long windowStartMillis,
        long windowEndMillis,
        long guardrailFindingCount,
        long triggeredCount,
        double triggerRate,
        long detectorErrorCount,
        double detectorErrorRate,
        Long missingConfidenceCount,
        Double missingConfidenceRate,
        Double confidenceCoverageRate,
        long confidenceCount,
        Long minDetectorLatencyMs,
        Double avgDetectorLatencyMs,
        Long maxDetectorLatencyMs
) {
}
